<a href="https://colab.research.google.com/github/aswit3/schoolofai_meetup3/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Why Pandas?

**IMQAV**
- Ingest
- Model
- Query
- **Analyze**
- **Visualize**

### Installation

In [0]:
!pip install pandas

### import

In [0]:
import pandas as pd
import numpy as np

### Series
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers,
Python objects, etc.)

##### Create series from NumPy array
number of labels in 'index' must be the same as the number of elements in array

In [0]:
my_series = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
my_series

a    1.440358
b   -1.650112
c    0.224989
d   -2.007446
e    0.705671
dtype: float64

In [0]:
print(type(my_series))

<class 'pandas.core.series.Series'>


##### Create series from NumPy array, without explicit index

In [0]:
my_series = pd.Series(np.random.randn(5))
my_series

0   -0.145365
1    1.515583
2    0.230423
3    0.482644
4   -0.262387
dtype: float64

##### Create series from Python dictionary

In [0]:
my_dict = {'a' : 'vizag', 'b' : 'Chennai', 'c' : 'Nellore'}
my_series2 = pd.Series(my_dict)
my_series2

a      vizag
b    Chennai
c    Nellore
dtype: object

##### Create series from scalar
If data is a scalar value, an index must be provided. The value will be repeated to match the length of index

In [0]:
pd.Series(2., index=['a', 'b', 'c', 'd', 'e', 'd'])

a    2.0
b    2.0
c    2.0
d    2.0
e    2.0
d    2.0
dtype: float64

### Dataframe

##### sample NumPy data

In [0]:
sample_numpy_data = np.array(np.arange(24)).reshape((6,4))
sample_numpy_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
my_dates_index = pd.date_range('20190620', periods=6)
my_dates_index

DatetimeIndex(['2019-06-20', '2019-06-21', '2019-06-22', '2019-06-23',
               '2019-06-24', '2019-06-25'],
              dtype='datetime64[ns]', freq='D')

In [0]:
sample_df = pd.DataFrame(sample_numpy_data, index=my_dates_index, columns=['A','B','C','D'])
sample_df

A   B   C   D
2019-06-20   0   1   2   3
2019-06-21   4   5   6   7
2019-06-22   8   9  10  11
2019-06-23  12  13  14  15
2019-06-24  16  17  18  19
2019-06-25  20  21  22  23

In [0]:
df_from_dictionary = pd.DataFrame({ 
                         'float' : 1.,
                         'time' : pd.Timestamp('20190622'),
                         'series' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'array' : np.array([3] * 4,dtype='int32'),
                         'categories' : pd.Categorical(["test","train","taxes","tools"]),
                         'place' : 'vizag' 
                      })
df_from_dictionary

float       time  series  array categories  place
0    1.0 2019-06-22     1.0      3       test  vizag
1    1.0 2019-06-22     1.0      3      train  vizag
2    1.0 2019-06-22     1.0      3      taxes  vizag
3    1.0 2019-06-22     1.0      3      tools  vizag

In [0]:
df_from_dictionary.dtypes

float                float64
time          datetime64[ns]
series               float32
array                  int32
categories          category
place                 object
dtype: object

In [0]:
sample_df.head(3)

A  B   C   D
2019-06-20  0  1   2   3
2019-06-21  4  5   6   7
2019-06-22  8  9  10  11

In [0]:
sample_df.tail(2)

A   B   C   D
2019-06-24  16  17  18  19
2019-06-25  20  21  22  23

In [0]:
sample_df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
sample_df.index

DatetimeIndex(['2019-06-20', '2019-06-21', '2019-06-22', '2019-06-23',
               '2019-06-24', '2019-06-25'],
              dtype='datetime64[ns]', freq='D')

In [0]:
sample_df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [0]:
sample_df.describe()

A          B          C          D
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [0]:
sample_df.shape

(6, 4)

In [0]:
sample_df

A   B   C   D
2019-06-20   0   1   2   3
2019-06-21   4   5   6   7
2019-06-22   8   9  10  11
2019-06-23  12  13  14  15
2019-06-24  16  17  18  19
2019-06-25  20  21  22  23

### Select data

In [0]:
sample_df.C

2019-06-20     2
2019-06-21     6
2019-06-22    10
2019-06-23    14
2019-06-24    18
2019-06-25    22
Freq: D, Name: C, dtype: int64

In [0]:
sample_df[1:4]

A   B   C   D
2019-06-21   4   5   6   7
2019-06-22   8   9  10  11
2019-06-23  12  13  14  15

In [0]:
sample_df['2019-06-21':'2019-06-24']

A   B   C   D
2019-06-21   4   5   6   7
2019-06-22   8   9  10  11
2019-06-23  12  13  14  15
2019-06-24  16  17  18  19

#### Selection by Label

In [0]:
sample_df.loc[:,['A','B']]

A   B
2019-06-20   0   1
2019-06-21   4   5
2019-06-22   8   9
2019-06-23  12  13
2019-06-24  16  17
2019-06-25  20  21

In [0]:
sample_df.loc['2019-06-21':'2019-06-24',['A','B']]

A   B
2019-06-21   4   5
2019-06-22   8   9
2019-06-23  12  13
2019-06-24  16  17

#### Selection by Position

In [0]:
sample_df

A   B   C   D
2019-06-20   0   1   2   3
2019-06-21   4   5   6   7
2019-06-22   8   9  10  11
2019-06-23  12  13  14  15
2019-06-24  16  17  18  19
2019-06-25  20  21  22  23

In [0]:
sample_df.iloc[3]

A    12
B    13
C    14
D    15
Name: 2019-06-23 00:00:00, dtype: int64

In [0]:
sample_df.iloc[1:3, 2:4]

C   D
2019-06-21   6   7
2019-06-22  10  11

In [0]:
sample_df.iloc[[0,1,3], [0,2]]

A   C
2019-06-20   0   2
2019-06-21   4   6
2019-06-23  12  14

### Missing Data

In [0]:
browser_index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']

browser_df = pd.DataFrame({
      'http_status': [200,200,404,404,301],
      'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
       index=browser_index)
browser_df

http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

In [0]:
new_index= ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10', 'Chrome']
browser_df_2 = browser_df.reindex(new_index)
browser_df_2

http_status  response_time
Safari               404.0           0.07
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

In [0]:
browser_df_2[browser_df_2['response_time'].isna()]

http_status  response_time
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN

In [0]:
browser_df_3 = browser_df_2.dropna(how='any')
browser_df_3

http_status  response_time
Safari        404.0           0.07
IE10          404.0           0.08
Chrome        200.0           0.02

In [0]:
browser_df_2.fillna(value=999.0)

http_status  response_time
Safari               404.0           0.07
Iceweasel            999.0         999.00
Comodo Dragon        999.0         999.00
IE10                 404.0           0.08
Chrome               200.0           0.02

In [0]:
sample_data = np.array(np.arange(24)).reshape((6,4))
sample_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
sample_df = pd.DataFrame(sample_data, columns=list('ABCD'))
sample_df

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23

In [0]:
def multiply_by_2(number):
  return number * 2

In [0]:
sample_df['A*2'] = sample_df['A'].apply(multiply_by_2)
sample_df


A   B   C   D  A*2
0   0   1   2   3    0
1   4   5   6   7    8
2   8   9  10  11   16
3  12  13  14  15   24
4  16  17  18  19   32
5  20  21  22  23   40

In [0]:
s = pd.Series(['Mumbai', 'Hyderabad', 'Coimbatore', 'Vizag', 'Bengalore','Chennai'])
sample_df['city'] =s
sample_df

A   B   C   D  A*2        city
0   0   1   2   3    0      Mumbai
1   4   5   6   7    8   Hyderabad
2   8   9  10  11   16  Coimbatore
3  12  13  14  15   24       Vizag
4  16  17  18  19   32   Bengalore
5  20  21  22  23   40     Chennai

In [0]:
sample_df['city'] = sample_df['city'].str.lower()

In [0]:
sample_df

A   B   C   D  A*2        city
0   0   1   2   3    0      mumbai
1   4   5   6   7    8   hyderabad
2   8   9  10  11   16  coimbatore
3  12  13  14  15   24       vizag
4  16  17  18  19   32   bengalore
5  20  21  22  23   40     chennai

In [0]:
sample_df['city'].str.len()

0     6
1     9
2    10
3     5
4     9
5     7
Name: city, dtype: int64

In [0]:
sample_df[sample_df['city'].str.contains('vizag')]

A   B   C   D  A*2   city
3  12  13  14  15   24  vizag

### Merge

In [0]:
left = pd.DataFrame({'my_key': ['K0', 'K1', 'K2', 'K3'],
 'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'my_key': ['K0', 'K1', 'K2', 'K3'],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3']})

In [0]:
left

In [0]:
right

In [0]:
result = pd.merge(left, right, on='my_key')
result

### Concat

In [0]:
import pandas as pd
import numpy as np

starting_date = '20190622'
sample_numpy_data = np.array(np.arange(24)).reshape((6,4))
dates_index = pd.date_range(starting_date, periods=6)
sample_df = pd.DataFrame(sample_numpy_data, index=dates_index, columns=list('ABCD'))

sample_df_2 = sample_df.copy()
sample_df_2['Fruits'] = ['apple', 'orange','banana','strawberry','blueberry','pineapple']

sample_series = pd.Series([1,2,3,4,5,6], index=pd.date_range(starting_date, periods=6))
sample_df_2['Extra Data'] = sample_series *3 +1

second_numpy_array = np.array(np.arange(len(sample_df_2)))  *100 + 7
sample_df_2['G'] = second_numpy_array

In [0]:
piece1 = sample_df_2[:2]
piece2 = sample_df_2[2:4]
piece3 = sample_df_2[4:]

In [0]:
piece1

In [0]:
piece2

In [0]:
pd.concat([piece1, piece2, piece3])

In [0]:
file_name_string = 'EmployeesWithGrades.xlsx'
employees_df = pd.read_excel(file_name_string, 'Sheet1', index_col=None, na_values=['NA'])

In [0]:
employees_df.head()

In [0]:
file_name_string_csv = 'Employees.csv'
employees_df.to_csv(file_name_string_csv )

In [0]:
employees_df.to_csv('new_emploees',index=False)

### Group by

In [0]:
df = pd.DataFrame([('bird', 'Falconiformes', 389.0),
                  ('bird', 'Psittaciformes', 24.0),
                  ('mammal', 'Carnivora', 80.2),
                  ('mammal', 'Primates', np.nan),
                  ('mammal', 'Carnivora', 58)],
                 index=['falcon', 'parrot', 'lion', 'monkey', 'leopard'],
                 columns=('class', 'order', 'max_speed'))

In [0]:
grouped = df.groupby('class')

In [0]:
for name,group in grouped:
   print(name, group)